### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Akalinsky/first_rails_app#1]
I'm seeing some hard-tabs throughout the project and [some especially inconsistent indentation here](https://github.com/Akalinsky/first_rails_app/blob/master/app/helpers/static_helper.rb). The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have *every* file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by Akalinsky** [comment]
Apologies for the late response. I fixed that issue and a few others. I use notepad ++ for much of my text editing and I already configured it for 2 space soft-tabs, i'm not certain why it didn't seem to be working.

**Comment by chrisvfritz** [comment]
:+1: Looks great! I just did some quick searching for Notepad++ plugins that might help it better recognize Rails files and it looks like [there are some tricks you can use](https://therubyway.wordpress.com/2008/11/23/rails-on-notepad/), but I haven't found anyone that's been able to hack it to completely work with Rails, especially the syntax highlighting for `.erb` files. :disappointed: 

If it becomes too much of a hassle, you may have an easier time with something like Sublime Text or Atom, simply because a lot more Rails developers use those editors and so there's much better community support.
